# coding: utf-8

"""
    assets-upload-api

    An autogenerated client for the assets-upload-api.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class AssetCreateRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'request': 'AssetCreateRequestRequest',
        'file_content': 'file'
    }

    attribute_map = {
        'request': 'request',
        'file_content': 'fileContent'
    }

    def __init__(self, request=None, file_content=None, local_vars_configuration=None):  # noqa: E501
        """AssetCreateRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._request = None
        self._file_content = None
        self.discriminator = None

        if request is not None:
            self.request = request
        self.file_content = file_content

    @property
    def request(self):
        """Gets the request of this AssetCreateRequest.  # noqa: E501


        :return: The request of this AssetCreateRequest.  # noqa: E501
        :rtype: AssetCreateRequestRequest
        """
        return self._request

    @request.setter
    def request(self, request):
        """Sets the request of this AssetCreateRequest.


        :param request: The request of this AssetCreateRequest.  # noqa: E501
        :type request: AssetCreateRequestRequest
        """

        self._request = request

    @property
    def file_content(self):
        """Gets the file_content of this AssetCreateRequest.  # noqa: E501


        :return: The file_content of this AssetCreateRequest.  # noqa: E501
        :rtype: file
        """
        return self._file_content

    @file_content.setter
    def file_content(self, file_content):
        """Sets the file_content of this AssetCreateRequest.


        :param file_content: The file_content of this AssetCreateRequest.  # noqa: E501
        :type file_content: file
        """
        if self.local_vars_configuration.client_side_validation and file_content is None:  # noqa: E501
            raise ValueError("Invalid value for `file_content`, must not be `None`")  # noqa: E501

        self._file_content = file_content

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssetCreateRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AssetCreateRequest):
            return True

        return self.to_dict() != other.to_dict()
