# coding: utf-8

"""
    assets-upload-api

    An autogenerated client for the assets-upload-api.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class GoogleProtobufWellKnownTypesTimestamp(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'seconds': 'int',
        'nanos': 'int'
    }

    attribute_map = {
        'seconds': 'seconds',
        'nanos': 'nanos'
    }

    def __init__(self, seconds=None, nanos=None, local_vars_configuration=None):  # noqa: E501
        """GoogleProtobufWellKnownTypesTimestamp - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._seconds = None
        self._nanos = None
        self.discriminator = None

        if seconds is not None:
            self.seconds = seconds
        if nanos is not None:
            self.nanos = nanos

    @property
    def seconds(self):
        """Gets the seconds of this GoogleProtobufWellKnownTypesTimestamp.  # noqa: E501


        :return: The seconds of this GoogleProtobufWellKnownTypesTimestamp.  # noqa: E501
        :rtype: int
        """
        return self._seconds

    @seconds.setter
    def seconds(self, seconds):
        """Sets the seconds of this GoogleProtobufWellKnownTypesTimestamp.


        :param seconds: The seconds of this GoogleProtobufWellKnownTypesTimestamp.  # noqa: E501
        :type seconds: int
        """

        self._seconds = seconds

    @property
    def nanos(self):
        """Gets the nanos of this GoogleProtobufWellKnownTypesTimestamp.  # noqa: E501


        :return: The nanos of this GoogleProtobufWellKnownTypesTimestamp.  # noqa: E501
        :rtype: int
        """
        return self._nanos

    @nanos.setter
    def nanos(self, nanos):
        """Sets the nanos of this GoogleProtobufWellKnownTypesTimestamp.


        :param nanos: The nanos of this GoogleProtobufWellKnownTypesTimestamp.  # noqa: E501
        :type nanos: int
        """

        self._nanos = nanos

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GoogleProtobufWellKnownTypesTimestamp):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GoogleProtobufWellKnownTypesTimestamp):
            return True

        return self.to_dict() != other.to_dict()
