# coding: utf-8

"""
    assets-upload-api

    An autogenerated client for the assets-upload-api.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class RobloxOperationscoreOperationserviceV1Beta1AssetInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'asset_id': 'int',
        'asset_version_number': 'int'
    }

    attribute_map = {
        'asset_id': 'assetId',
        'asset_version_number': 'assetVersionNumber'
    }

    def __init__(self, asset_id=None, asset_version_number=None, local_vars_configuration=None):  # noqa: E501
        """RobloxOperationscoreOperationserviceV1Beta1AssetInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._asset_id = None
        self._asset_version_number = None
        self.discriminator = None

        if asset_id is not None:
            self.asset_id = asset_id
        if asset_version_number is not None:
            self.asset_version_number = asset_version_number

    @property
    def asset_id(self):
        """Gets the asset_id of this RobloxOperationscoreOperationserviceV1Beta1AssetInfo.  # noqa: E501


        :return: The asset_id of this RobloxOperationscoreOperationserviceV1Beta1AssetInfo.  # noqa: E501
        :rtype: int
        """
        return self._asset_id

    @asset_id.setter
    def asset_id(self, asset_id):
        """Sets the asset_id of this RobloxOperationscoreOperationserviceV1Beta1AssetInfo.


        :param asset_id: The asset_id of this RobloxOperationscoreOperationserviceV1Beta1AssetInfo.  # noqa: E501
        :type asset_id: int
        """

        self._asset_id = asset_id

    @property
    def asset_version_number(self):
        """Gets the asset_version_number of this RobloxOperationscoreOperationserviceV1Beta1AssetInfo.  # noqa: E501


        :return: The asset_version_number of this RobloxOperationscoreOperationserviceV1Beta1AssetInfo.  # noqa: E501
        :rtype: int
        """
        return self._asset_version_number

    @asset_version_number.setter
    def asset_version_number(self, asset_version_number):
        """Sets the asset_version_number of this RobloxOperationscoreOperationserviceV1Beta1AssetInfo.


        :param asset_version_number: The asset_version_number of this RobloxOperationscoreOperationserviceV1Beta1AssetInfo.  # noqa: E501
        :type asset_version_number: int
        """

        self._asset_version_number = asset_version_number

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RobloxOperationscoreOperationserviceV1Beta1AssetInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RobloxOperationscoreOperationserviceV1Beta1AssetInfo):
            return True

        return self.to_dict() != other.to_dict()
