# coding: utf-8

"""
    assets-upload-api

    An autogenerated client for the assets-upload-api.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class RobloxAssetsManagementAssetsUploadApiMultipartUploadChunkCompleteRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'chunk_num': 'int',
        'e_tag': 'str'
    }

    attribute_map = {
        'chunk_num': 'chunkNum',
        'e_tag': 'eTag'
    }

    def __init__(self, chunk_num=None, e_tag=None, local_vars_configuration=None):  # noqa: E501
        """RobloxAssetsManagementAssetsUploadApiMultipartUploadChunkCompleteRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._chunk_num = None
        self._e_tag = None
        self.discriminator = None

        if chunk_num is not None:
            self.chunk_num = chunk_num
        self.e_tag = e_tag

    @property
    def chunk_num(self):
        """Gets the chunk_num of this RobloxAssetsManagementAssetsUploadApiMultipartUploadChunkCompleteRequest.  # noqa: E501


        :return: The chunk_num of this RobloxAssetsManagementAssetsUploadApiMultipartUploadChunkCompleteRequest.  # noqa: E501
        :rtype: int
        """
        return self._chunk_num

    @chunk_num.setter
    def chunk_num(self, chunk_num):
        """Sets the chunk_num of this RobloxAssetsManagementAssetsUploadApiMultipartUploadChunkCompleteRequest.


        :param chunk_num: The chunk_num of this RobloxAssetsManagementAssetsUploadApiMultipartUploadChunkCompleteRequest.  # noqa: E501
        :type chunk_num: int
        """

        self._chunk_num = chunk_num

    @property
    def e_tag(self):
        """Gets the e_tag of this RobloxAssetsManagementAssetsUploadApiMultipartUploadChunkCompleteRequest.  # noqa: E501


        :return: The e_tag of this RobloxAssetsManagementAssetsUploadApiMultipartUploadChunkCompleteRequest.  # noqa: E501
        :rtype: str
        """
        return self._e_tag

    @e_tag.setter
    def e_tag(self, e_tag):
        """Sets the e_tag of this RobloxAssetsManagementAssetsUploadApiMultipartUploadChunkCompleteRequest.


        :param e_tag: The e_tag of this RobloxAssetsManagementAssetsUploadApiMultipartUploadChunkCompleteRequest.  # noqa: E501
        :type e_tag: str
        """

        self._e_tag = e_tag

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RobloxAssetsManagementAssetsUploadApiMultipartUploadChunkCompleteRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RobloxAssetsManagementAssetsUploadApiMultipartUploadChunkCompleteRequest):
            return True

        return self.to_dict() != other.to_dict()
