# coding: utf-8

"""
    assets-upload-api

    An autogenerated client for the assets-upload-api.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class RobloxOpenCloudAssetsV1CreationContext(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'creator': 'RobloxOpenCloudAssetsV1Creator',
        'expected_price': 'int'
    }

    attribute_map = {
        'creator': 'creator',
        'expected_price': 'expectedPrice'
    }

    def __init__(self, creator=None, expected_price=None, local_vars_configuration=None):  # noqa: E501
        """RobloxOpenCloudAssetsV1CreationContext - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._creator = None
        self._expected_price = None
        self.discriminator = None

        if creator is not None:
            self.creator = creator
        if expected_price is not None:
            self.expected_price = expected_price

    @property
    def creator(self):
        """Gets the creator of this RobloxOpenCloudAssetsV1CreationContext.  # noqa: E501


        :return: The creator of this RobloxOpenCloudAssetsV1CreationContext.  # noqa: E501
        :rtype: RobloxOpenCloudAssetsV1Creator
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """Sets the creator of this RobloxOpenCloudAssetsV1CreationContext.


        :param creator: The creator of this RobloxOpenCloudAssetsV1CreationContext.  # noqa: E501
        :type creator: RobloxOpenCloudAssetsV1Creator
        """

        self._creator = creator

    @property
    def expected_price(self):
        """Gets the expected_price of this RobloxOpenCloudAssetsV1CreationContext.  # noqa: E501


        :return: The expected_price of this RobloxOpenCloudAssetsV1CreationContext.  # noqa: E501
        :rtype: int
        """
        return self._expected_price

    @expected_price.setter
    def expected_price(self, expected_price):
        """Sets the expected_price of this RobloxOpenCloudAssetsV1CreationContext.


        :param expected_price: The expected_price of this RobloxOpenCloudAssetsV1CreationContext.  # noqa: E501
        :type expected_price: int
        """

        self._expected_price = expected_price

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RobloxOpenCloudAssetsV1CreationContext):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RobloxOpenCloudAssetsV1CreationContext):
            return True

        return self.to_dict() != other.to_dict()
