# coding: utf-8

"""
    assets-upload-api

    An autogenerated client for the assets-upload-api.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class RobloxOpenCloudAssetsV1Creator(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'user_id': 'int',
        'group_id': 'int',
        'creator_id_case': 'RobloxOpenCloudAssetsV1CreatorCreatorIdOneofCase'
    }

    attribute_map = {
        'user_id': 'userId',
        'group_id': 'groupId',
        'creator_id_case': 'creatorIdCase'
    }

    def __init__(self, user_id=None, group_id=None, creator_id_case=None, local_vars_configuration=None):  # noqa: E501
        """RobloxOpenCloudAssetsV1Creator - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._user_id = None
        self._group_id = None
        self._creator_id_case = None
        self.discriminator = None

        if user_id is not None:
            self.user_id = user_id
        if group_id is not None:
            self.group_id = group_id
        if creator_id_case is not None:
            self.creator_id_case = creator_id_case

    @property
    def user_id(self):
        """Gets the user_id of this RobloxOpenCloudAssetsV1Creator.  # noqa: E501


        :return: The user_id of this RobloxOpenCloudAssetsV1Creator.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this RobloxOpenCloudAssetsV1Creator.


        :param user_id: The user_id of this RobloxOpenCloudAssetsV1Creator.  # noqa: E501
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def group_id(self):
        """Gets the group_id of this RobloxOpenCloudAssetsV1Creator.  # noqa: E501


        :return: The group_id of this RobloxOpenCloudAssetsV1Creator.  # noqa: E501
        :rtype: int
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this RobloxOpenCloudAssetsV1Creator.


        :param group_id: The group_id of this RobloxOpenCloudAssetsV1Creator.  # noqa: E501
        :type group_id: int
        """

        self._group_id = group_id

    @property
    def creator_id_case(self):
        """Gets the creator_id_case of this RobloxOpenCloudAssetsV1Creator.  # noqa: E501


        :return: The creator_id_case of this RobloxOpenCloudAssetsV1Creator.  # noqa: E501
        :rtype: RobloxOpenCloudAssetsV1CreatorCreatorIdOneofCase
        """
        return self._creator_id_case

    @creator_id_case.setter
    def creator_id_case(self, creator_id_case):
        """Sets the creator_id_case of this RobloxOpenCloudAssetsV1Creator.


        :param creator_id_case: The creator_id_case of this RobloxOpenCloudAssetsV1Creator.  # noqa: E501
        :type creator_id_case: RobloxOpenCloudAssetsV1CreatorCreatorIdOneofCase
        """

        self._creator_id_case = creator_id_case

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RobloxOpenCloudAssetsV1Creator):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RobloxOpenCloudAssetsV1Creator):
            return True

        return self.to_dict() != other.to_dict()
